<?php
// Set basic CORS headers EARLY (before config loads) to handle OPTIONS requests immediately
if (php_sapi_name() !== 'cli' && isset($_SERVER['REQUEST_METHOD'])) {
    $origin = $_SERVER['HTTP_ORIGIN'] ?? null;
    
    // Extract origin from referer if HTTP_ORIGIN is not set
    if (!$origin && isset($_SERVER['HTTP_REFERER'])) {
        $referer = $_SERVER['HTTP_REFERER'];
        $parsed = parse_url($referer);
        if ($parsed) {
            $origin = $parsed['scheme'] . '://' . $parsed['host'];
            if (isset($parsed['port']) && !in_array($parsed['port'], [80, 443])) {
                $origin .= ':' . $parsed['port'];
            }
        }
    }
    
    // Normalize origin
    if ($origin) {
        $origin = rtrim($origin, '/');
    }
    
    // CRITICAL: Never use wildcard with credentials - always set specific origin
    if ($origin) {
        header("Access-Control-Allow-Origin: $origin");
    } else {
        // Fallback to common development origin
        header("Access-Control-Allow-Origin: http://localhost:5000");
    }
    header("Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS");
    header("Access-Control-Allow-Headers: Content-Type,Authorization,X-Requested-With");
    header("Access-Control-Allow-Credentials: true");
    
    // Handle preflight OPTIONS request immediately
    if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
        http_response_code(200);
        exit;
    }
}

require_once __DIR__ . '/config.php';

// Database Connection - Auto-generated by Lerumos PHP Maker
$dbPath = DB_PATH;
if (DB_TYPE === 'sqlite') {
    // Handle relative paths
    if (!file_exists($dbPath) && file_exists(__DIR__ . '/' . basename($dbPath))) {
        $dbPath = __DIR__ . '/' . basename($dbPath);
    }
    $db = new PDO("sqlite:$dbPath");
} else {
    // MySQL/PostgreSQL support (if needed)
    $dbHost = getenv('DB_HOST') ?: 'localhost';
    $dbPort = getenv('DB_PORT') ?: '3306';
    $dbName = getenv('DB_NAME') ?: 'social_media';
    $dbUser = getenv('DB_USER') ?: 'root';
    $dbPassword = getenv('DB_PASSWORD') ?: '';
    
    if (DB_TYPE === 'mysql') {
        $db = new PDO("mysql:host=$dbHost;port=$dbPort;dbname=$dbName", $dbUser, $dbPassword);
    } elseif (DB_TYPE === 'pgsql') {
        $db = new PDO("pgsql:host=$dbHost;port=$dbPort;dbname=$dbName", $dbUser, $dbPassword);
    } else {
        throw new Exception("Unsupported database type: " . DB_TYPE);
    }
}

$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);

// SQLite-specific optimizations
if (DB_TYPE === 'sqlite') {
    $db->exec("PRAGMA foreign_keys = ON");
    $db->exec("PRAGMA journal_mode = WAL");
}

// CORS Headers (only set if running via web server, not CLI)
// Must be set before any output or session operations
if (php_sapi_name() !== 'cli' && isset($_SERVER['REQUEST_METHOD'])) {
    // Get origin from request
    $origin = $_SERVER['HTTP_ORIGIN'] ?? $_SERVER['HTTP_REFERER'] ?? null;
    
    // If no origin, try to extract from referer
    if (!$origin && isset($_SERVER['HTTP_REFERER'])) {
        $referer = $_SERVER['HTTP_REFERER'];
        $parsed = parse_url($referer);
        if ($parsed) {
            $origin = $parsed['scheme'] . '://' . $parsed['host'];
            if (isset($parsed['port'])) {
                $origin .= ':' . $parsed['port'];
            }
        }
    }
    
    // Normalize origin
    if ($origin && $origin !== '*') {
        $origin = rtrim($origin, '/');
        // Handle 127.0.0.1 -> localhost conversion
        if (strpos($origin, '127.0.0.1') !== false) {
            $originLocalhost = str_replace('127.0.0.1', 'localhost', $origin);
            if (in_array($originLocalhost, CORS_ALLOWED_ORIGINS)) {
                $origin = $originLocalhost;
            }
        }
        // Handle localhost -> 127.0.0.1 conversion
        if (strpos($origin, 'localhost') !== false) {
            $origin127 = str_replace('localhost', '127.0.0.1', $origin);
            if (in_array($origin127, CORS_ALLOWED_ORIGINS)) {
                $origin = $origin127;
            }
        }
    }
    
    // Set CORS headers - NEVER use wildcard with credentials
    if ($origin && (in_array($origin, CORS_ALLOWED_ORIGINS) || in_array('*', CORS_ALLOWED_ORIGINS))) {
        header("Access-Control-Allow-Origin: $origin");
    } elseif ($origin) {
        // Development: allow the requesting origin
        header("Access-Control-Allow-Origin: $origin");
    } else {
        // Fallback to common development origin
        header("Access-Control-Allow-Origin: http://localhost:5000");
    }

    header("Content-Type: application/json");
    header("Access-Control-Allow-Methods: " . CORS_ALLOWED_METHODS);
    header("Access-Control-Allow-Headers: " . CORS_ALLOWED_HEADERS);
    header("Access-Control-Allow-Credentials: true");
    header("Access-Control-Max-Age: 86400"); // Cache preflight for 24 hours

    // Handle preflight OPTIONS request
    if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
        http_response_code(200);
        exit;
    }
}

function requireAuth() {
    session_start();
    if (!isset($_SESSION['user_id'])) {
        http_response_code(401);
        echo json_encode(['success' => false, 'error' => 'Authentication required']);
        exit;
    }
    return $_SESSION['user_id'];
}

function sanitizeInput($input) {
    return htmlspecialchars(strip_tags(trim($input)));
}

function validateEmail($email) {
    return filter_var($email, FILTER_VALIDATE_EMAIL);
}
?>